export const NODES_CAPS = {
  TERMINAL: 1,
  GUI: 2,
  FS: 4,
  NET: 8,
  USERS: 16
}

export const PROTOCOLS = {
  SSH: 'SSH',
  SSH2: 'SSH2',
  FTP: 'FTP',
  WEBDAV: 'WEBDAV',
  RDP: 'RDP',
  VNC: 'VNC',
  SERIALPORT: 'SERIALPORT',
  LOCAL: 'LOCAL',
  TELNET: 'TELNET',
  LOCALSHELL: 'LOCALSHELL'
}

export const PROTOCOL_CAPS_MAP: { [key: string]: number } = {
  SSH: NODES_CAPS.TERMINAL | NODES_CAPS.GUI | NODES_CAPS.FS | NODES_CAPS.NET | NODES_CAPS.USERS,
  SSH2: NODES_CAPS.TERMINAL | NODES_CAPS.GUI | NODES_CAPS.FS | NODES_CAPS.NET | NODES_CAPS.USERS,
  FTP: NODES_CAPS.FS,
  WEBDAV: NODES_CAPS.FS,
  RDP: NODES_CAPS.GUI,
  VNC: NODES_CAPS.GUI,
  SERIALPORT: NODES_CAPS.TERMINAL,
  TELNET: NODES_CAPS.TERMINAL,
  LOCALSHELL: NODES_CAPS.TERMINAL,
  LOCAL: NODES_CAPS.TERMINAL | NODES_CAPS.FS
}

export const TERMINAL_FEATURES = {
  VT100: 1,
  XTERM: 2,
  LINUX: 4
}

export const GUI_FEATURES = {
  X11: 1,
  RDP: 2,
  VNC: 4
}

export const FS_FEATURES = {
  OPEN: 1,
  CLOSE: 2,
  READ: 4,
  WRITE: 8,
  FSTAT: 16,
  FSETSTAT: 32,
  FUTIMES: 64,
  FCHOWN: 128,
  FCHMOD: 256,
  OPENDIR: 512,
  READDIR: 1024,
  UNLINK: 2048,
  RENAME: 4096,
  MKDIR: 8192,
  RMDIR: 16384,
  STAT: 32768,
  LSTAT: 65536,
  SETSTAT: 1 << 17,
  UTIMES: 1 << 18,
  CHOWN: 1 << 19,
  CHMOD: 1 << 20,
  READLINK: 1 << 21,
  SYMLINK: 1 << 22,
  REALPATH: 1 << 23
}

export const NET_FEATURES = {
  FORWARD_IN: 1,
  FORWARD_OUT: 2,
  TUNNEL: 4
}
